apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chat
spec:
  selector:
    matchLabels:
      app: chat
  replicas: 3
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: muryginm/chat:1.2
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: '6379'
        ports:
        - containerPort: 80
